### ISSUE TITLE
Errore "Cannot allocate memory" con opzione -csv

### ISSUE THREAD

**Issue by marcomarsala** [peppelinux/xt_recent_parser#2]
Utilizzando lo script con l'opzione `-csv` si riceve il seguente errore. Funziona regolarmente con l'opzione `-txt`.

```
# python3 iptables_xt_recent_parser.py -csv
XT_RECENT python parser
<giuseppe.demarco@unical.it>

Parsing file: /proc/net/xt_recent/DEFAULT
Traceback (most recent call last):
  File "iptables_xt_recent_parser.py", line 302, in <module>
    xt.csv()
  File "iptables_xt_recent_parser.py", line 236, in csv
    self.parse()
  File "iptables_xt_recent_parser.py", line 225, in parse
    row_dt = row.convert_jiffies()
  File "iptables_xt_recent_parser.py", line 175, in convert_jiffies
    jt = JiffyTimeConverter()
  File "iptables_xt_recent_parser.py", line 40, in __init__
    self.jiffies = JiffyTimeConverter.system_jiffies()
  File "iptables_xt_recent_parser.py", line 98, in system_jiffies
    q = re.search(_jiffies_pattern, f.read())
OSError: [Errno 12] Cannot allocate memory

```

**Comment by peppelinux** [comment]
Ciao Marco,

please give me some more info about the python version you're using and the number of rows exported in the txt. Which OS you're using, distribution.

The Exception seems to be strictly related to OS, probably you have some customized (sysctl) kernel paramenters, isn't so?

**Comment by marcomarsala** [comment]
Python 3.4.10 on CentOS 6.9.
In txt there are 100 rows as per xt_recent default.
sysctl parameters for xt_recent wasn't customized.

**Comment by marcomarsala** [comment]
It is working today. Maybe it really was a memory issue.

```
# free -m
             total       used       free     shared    buffers     cached
Mem:          8001       7811        189         32          0        297
-/+ buffers/cache:       7513        488
Swap:         4063       4063          0

```

**Comment by peppelinux** [comment]
Yes it was, thank you for the feedback
